/*
 * scenario.js — "The Noatak Dossier" (Phase 1 hub-and-spoke TRIAL room).
 *
 * This is a mechanics demo for the graph engine, not finished course content.
 * It reuses the Alaska dataset and questions as three independent "spokes" so
 * the answer-key indices are known (correct = 18, 3, 1 — see decoder DEMO_KEY),
 * and adds a "boss" figure task gated behind resolving 2 of the 3 spokes.
 *
 * GRAPH schema (vs the linear `steps` array):
 *   - `nodes`: each spoke has { key, type:"spoke", technique, title, prompt,
 *     options, correct, maxAttempts, feedback }. The boss has
 *     { key, type:"boss", technique, title, brief, figureSpec } and no MC — it
 *     produces a figure graded by hand.
 *   - `bossGate.requires`: how many spokes must be RESOLVED (solved or
 *     attempts-exhausted) before the boss unlocks.
 *
 * Node `correct` is a 0-based index into `options`, 0-31 (5 bits).
 */
window.SCENARIO = {
  id: 2,
  slug: "demo_hub",
  title: "The Noatak Dossier",

  music: null,
  keepBackground: true,

  // Point-and-click scene (rung 2). The map becomes this illustration and each
  // node's `pos` anchors its hotspot on the matching object in the art.
  // Generated by authoring/generate_scene.py from authoring/prompts/demo_hub_station.txt.
  scene: { image: "scene/station.png" },

  packages: ["readr", "dplyr", "ggplot2"],
  datasets: [
    {
      name: "alaska_lake_data",
      url: "https://thebustalab.github.io/phylochemistry/sample_data/alaska_lake_data.csv",
    },
  ],
  setup: "suppressMessages({library(readr); library(dplyr); library(ggplot2)})",

  screen1: {
    image: "https://cdn.midjourney.com/6b9bdd4a-5852-41ba-83a7-41762e6c29d7/0_0.png",
    title: "Search & Rescue — case room",
    story: `
      <p>The Noatak file is open on the table, and this time it isn't one
      question but a whole dossier of loose threads. Work them in whatever order
      you like — some are quick, some need a closer look at the data.</p>
      <p>Clear enough of the leads and the room opens onto the final task: the
      figure that goes in the rescue brief.</p>
      <p class="byline">Enter your x500 to sign the case log, then step inside.</p>
    `,
    enterLabel: "Open the dossier →",
  },

  briefing: `
    <p>The dataset <code>alaska_lake_data</code> is loaded. Columns include
    <code>lake</code>, <code>park</code> (preserve code; Noatak is
    <code>NOAT</code>), and <code>water_temp</code>. Explore on the left, then
    work the leads on the right in any order.</p>
  `,

  starterCode:
    'library(dplyr)\nlibrary(ggplot2)\n\nalaska_lake_data %>%\n  filter(park == "NOAT") %>%\n  ggplot() +\n  geom_point(aes(x = water_temp, y = lake))',

  nodes: [
    {
      key: "warm_lake",
      type: "spoke",
      technique: "data visualisation",
      pos: { x: 11, y: 38 }, // the topographic wall map, left
      title: "Lead 1 — the warm lake",
      prompt:
        "Filter to Noatak (<code>park == \"NOAT\"</code>) and compare water temperature across lakes. One lake is dramatically warmer. Which lake should the team search first?",
      options: [
        "Devil_Mountain_Lake", "Imuruk_Lake", "Kuzitrin_Lake", "Lava_Lake",
        "North_Killeak_Lake", "White_Fish_Lake", "Iniakuk_Lake", "Kurupa_Lake",
        "Lake_Matcharak", "Lake_Selby", "Nutavukti_Lake", "Summit_Lake",
        "Takahula_Lake", "Walker_Lake", "Wild_Lake", "Desperation_Lake",
        "Feniak_Lake", "Lake_Kangilipak", "Lake_Narvakrak", "Okoklik_Lake",
      ],
      correct: 18, // Lake_Narvakrak
      maxAttempts: 4,
      feedback: {
        correct:
          "That's it — <strong>Lake Narvakrak</strong> sits far above every other Noatak lake.",
        wrong: [
          "Filter to <code>park == \"NOAT\"</code> first, then look for the single point far to the right.",
          "Map temperature to x and lake to y so the outlier is easy to spot.",
          "One Noatak lake is near 18&nbsp;°C while the others sit below 7&nbsp;°C.",
        ],
        reveal:
          "The warm outlier was <strong>Lake Narvakrak</strong> (~18&nbsp;°C). Recording your last answer.",
      },
    },
    {
      key: "how_warm",
      type: "spoke",
      technique: "reading a plot",
      pos: { x: 46, y: 64 }, // the laptop showing a chart, centre desk
      title: "Lead 2 — how warm?",
      prompt:
        "Roughly how warm is that outlier lake, compared with the others clustered together?",
      options: ["About 3 °C", "About 6 °C", "About 12 °C", "About 18 °C"],
      correct: 3,
      maxAttempts: 3,
      feedback: {
        correct: "Right — about <strong>18&nbsp;°C</strong>, while the rest sit near freezing.",
        wrong: [
          "Read the x-position of the outlier point off your plot.",
          "The other lakes cluster around 3–6&nbsp;°C; the outlier is far to the right.",
        ],
        reveal: "It reads close to 18&nbsp;°C. Moving on.",
      },
    },
    {
      key: "why_signal",
      type: "spoke",
      technique: "inference",
      pos: { x: 82, y: 63 }, // the two-way radio with the amber dial, right
      title: "Lead 3 — the impossible signal",
      prompt:
        "The beacon kept transmitting for hours, long past the 25-minute cold-water survival window. Given your finding, what is the most likely explanation?",
      options: [
        "The beacon simply malfunctioned and the reading means nothing.",
        "Ethan reached the one unusually warm lake, which kept him alive.",
        "The cold slowed the beacon's battery, faking a long signal.",
        "Another aircraft's beacon was overlapping the frequency.",
      ],
      correct: 1,
      maxAttempts: 2,
      feedback: {
        correct:
          "Exactly — a warm lake in a freezing preserve is the one place a survival timeline stretches to hours.",
        wrong: [
          "Tie it to your finding: one lake is far warmer than the rest. What would that mean for someone in the water?",
        ],
        reveal: "The intended reading: the warm lake explains the long signal. Moving on.",
      },
    },
    {
      key: "boss",
      type: "boss",
      technique: "the rescue-brief figure",
      pos: { x: 64, y: 30 }, // the window onto the frozen lake, back
      title: "★ Final challenge — the brief figure",
      brief:
        "You've placed the warm lake and explained the signal. Now produce the single figure that goes at the top of the rescue brief: Noatak's lakes ranked by water temperature, with the outlier unmistakable at a glance.",
      figureSpec:
        "all NOAT lakes, water temperature on one axis, the warm outlier clearly standing apart — a plot a pilot could read in two seconds.",
    },
  ],

  bossGate: { requires: 2 }, // resolve 2 of the 3 leads to unlock the boss

  finishMessage: `
    <p>Dossier cleared and the brief figure is ready. Copy your case code below
    and submit it to Canvas along with your figure.</p>
  `,
};
